export const produto = {
    valor: 250,
    sale: 50/100,
    newValor: 250 * (50/100),
    onCart: 0,
    name: 'Fall Limited Edition Snakers',
    description: `These low-profile sneakers are your perfect casual wear companion. Featuring a durable
    rubber outer sole, they´ll whitstand everything the weather can offer.`,
    img1: '/image-product-1.jpg',
    img2: '/image-product-2.jpg',
    img3: '/image-product-3.jpg',
    img4: '/image-product-4.jpg'
}
